# Generated by Django 5.1.7 on 2025-04-16 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_rename_products_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.0, max_digits=5),
            preserve_default=False,
        ),
    ]
